---
project-file-path: "./QRCode.xcodeproj"
default-scheme: QRCode
default-sdk: iphoneos10.1
default-32bit-test-device: "'iOS Simulator,OS=10.1,name=iPhone 5'"
default-64bit-test-device: "'iOS Simulator,OS=10.1,name=iPhone 7'"
app-targets:
- QRCode
- QRCodeExamples
test-targets:
- QRCode
- QRCodeTests
ui-test-targets: []
provisioning-path: "./provisioning"
crashlytics-framework-path:
