---
project-file-path: "/Users/dschmidt/workspace/QRCode/QRCode.xcodeproj"
default-scheme: QRCode
default-sdk: iphoneos10.2
default-32bit-test-device: "'iOS Simulator,OS=10.2,name=iPhone 5'"
default-64bit-test-device: "'iOS Simulator,OS=10.2,name=iPhone 7'"
app-targets:
- QRCode
test-targets:
- QRCodeTests
ui-test-targets: []
provisioning-path: "/Users/dschmidt/workspace/QRCode/provisioning"
crashlytics-framework-path: 
